### ISSUE TITLE
Locks up Firefox

### ISSUE THREAD

**Issue by nirvdrum** [fczbkk/github-issues-extension#9]
I've been trying to track down why my Firefox completely locks up on various sites.  One that routinely locks up is the [Amazon Web Services Console](https://console.aws.amazon.com/).  I thought it was just a bug in Firefox as it seems the browser has had problem with Amazon.com in the past.  However, I just went through all of my add-ons one-by-one and discovered that if I disable this add-on the problem goes away.

Unfortunately, because the browser is unresponsive, I can't use Firefox's built-in profiler.  I can try to work it out with system-level debug tools.  But I thought I would report it here and maybe someone can work out the issue by inspection.

**Comment by fczbkk** [comment]
Sent the new release to Mozilla Addons. Your extension should be updated shortly after they review it.
